### ISSUE TITLE
Suggest Org allows for empty form to be submitted.

### ISSUE THREAD

**Issue by Alfredo-Moreira** [weareinreach/inreach-catalog#154]
src/suggestion.js/line 417 (this.organizeData())

The function does not sanitize the form and allows an empty form to be submitted.

![Screen Shot 2021-06-12 at 10 25 32 PM](https://user-images.githubusercontent.com/11844106/121795435-0d31c880-cbce-11eb-8583-ff47cd8350cb.png)

**Comment by trigal2012** [comment]
addressed in this PR
https://github.com/asylum-connect/asylumconnect-catalog/pull/238
